### ISSUE TITLE
Error updating options: e.replace is not a function

### ISSUE THREAD

**Issue by VincentSC** [voidquark/grafana-dashboards#2]
First I want to say I'm totally new to Grafana. I've got Gitlab with built-in Grafana and a separate Loki-docker.

When opening the dashboard, I get 6 errors like this:
```
Templating [instance]
Error updating options: e.replace is not a function
```
And an empty dashboard.
![Screenshot 2023-03-15 at 17-03-03 Nextcloud Logs - Grafana](https://user-images.githubusercontent.com/5090382/225369339-e86a02ad-c9b7-41cc-824f-eb3b132f0da4.png)

Data seems to be received, according to the explorer:
![Screenshot 2023-03-15 at 17-05-13 Nextcloud Logs - Grafana](https://user-images.githubusercontent.com/5090382/225369974-0e647fd5-a797-46a0-ad2f-6d4f4bbcf8c6.png)

Versions:
- Grafana v7.5.16 (c0e2ad126c) - this is what Gitlab provides... I secretly think this is the problem
- Loki `latest` from Docker

Is there a way to fix this other than not using the Gitlab-version?

**Comment by voidquark** [comment]
You are right. The problem is due to the old version of Grafana. I strongly advise you to use the latest version of Grafana. Unfortunately, the dashboard requires this function.

**Comment by VincentSC** [comment]
For those who are searching for this problem: Gitlab's internal Grafana is outdated for several popular dashboards. Installing a separate Grafana solves the problem.

For full convenience, this is the docker-compose.yml for nginx-proxy:
```
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
    restart: unless-stopped
    volumes:
      - ./volumes/prometheus_config:/etc/prometheus
      - ./volumes/prometheus_data:/prometheus
    environment:
      - VIRTUAL_HOST=${P_DOMAIN}
      - LETSENCRYPT_HOST=${P_DOMAIN}
      - VIRTUAL_PORT=9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=xxx
    volumes:
      - ./volumes/grafana_datasources:/etc/grafana/provisioning/datasources
      - ./volumes/grafana_data:/var/lib/grafana
      - ./volumes/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.streamhpc.net
      - VIRTUAL_HOST=${G_DOMAIN}
      - LETSENCRYPT_HOST=${G_DOMAIN}
      - VIRTUAL_PORT=3000

networks:
  default:
    external:
      name: nginx-proxy
```

Make sure to create "grafana.ini" as a file, add the required variables to `.env`, and chown the [grafana directories to 472:472](https://www.google.com/search?q=grafana+chown+472).
