### ISSUE TITLE
[BUG] [SSH Logs] Parse error : queries require at least one regexp or equality matcher that does not have an empty-compatible value.

### ISSUE THREAD

**Issue by perrfect** [voidquark/grafana-dashboards#6]
**Loki Version:** [2.9.6]
**Grafana Version:** [10.4.1]
**Promtail Version:** [2.9.6]
**Dashboard Name:** [SSH Logs]

Hello. I'm using your SSH Logs dashboard and all the time getting the error:
```
Error
parse error : queries require at least one regexp or equality matcher that does not have an empty-compatible value. For instance, app=~".*" does not meet this requirement, but app=~".+" will
```

In my case promtail.conf looks like:

```
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: messages
      __path__: /var/log/messages
- job_name: audit
  static_configs:
  - targets:
      - localhost
    labels:
      job: audit
      __path__: /var/log/audit/*.log
- job_name: secure
  static_configs:
  - targets:
      - localhost
    labels:
      job: secure
      __path__: /var/log/secure
```
And in a grafana I chose all **Label name**, all **Label Value** and all **Job**
![1](https://github.com/voidquark/grafana-dashboards/assets/39082702/dc21aed1-f02d-46c3-8f00-16f716830195)

Could you please help me solve the problem?
